--CREATE TABLE [dbo].[UserRole]
--(
--  [Id]              INT IDENTITY(1, 1)  NOT NULL,
--  [RoleId]          INT                 NOT NULL,
--  [UserId]          INT                 NOT NULL,

--  CONSTRAINT [PK_AppUserRole]
--    PRIMARY KEY CLUSTERED ([Id] ASC),
--  CONSTRAINT [UK_AppUserRole]
--    UNIQUE ([UserId] ASC, [RoleId])
--)